#!/bin/bash

#This bash script reads files with |___"num1:num2"____| format lines adds them and finds the #file
#and collum which have the biggest sum of all files.
#First, separates each line from ':', and creates a matrix witch contains num1 and num2.
#Second, it adds each number and if they are bigger than the last sum it stores the value
#of sum, file name and column.
#Then shifts the input and if there is any other file left it does the same thing again.
#Last, prints file name , column and max sum.
#
#call     ./findMaxColumn  ./inputFile  ./inputFile2 ./inputFile3 .... ./inputFileN
#output    fileName, Column and max sum

input=$*

sum=0
temp=0
tempcolumn=0
tempfile="ERROR NO INPUT FILE"

for str
do
  	i=0
  	var=$1
	  IFS=':'
	  while IFS= read line
	   do
    		arr=( $line )
    		a=${arr[0]}
    		b=${arr[1]}


	    	i=$((i+1))
	    	temp=$((a + b))

	   	if [ "$temp" -ge "$sum" ]
	    	then
	        	tempcolumn=$i
	        	sum=$temp
	        	tempfile=$var
	        fi

    	done < "$var"

	shift

done

echo "FILE:$tempfile,COLUMN:$tempcolumn,sum=$sum"
